#!groovy
properties([disableConcurrentBuilds()])

pipeline {
    agent {
        label 'master || built-in'
        }
    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
        timestamps()
    }
    stages {
        stage("build docker image") {
            steps {
                echo "=========== start builde image ========="
                dir ('plug_get_post') {
                    sh 'docker build -t plug. '
                    }
                    }}}
}
