services:

  jvm-app:
    image: plug_get_post
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-javaagent:/docker/jolokia-agent-jvm-javaagent.jar
    volumes:
      - /docker/jolokia-agent-jvm-javaagent.jar:/docker/jolokia-agent-jvm-javaagent.jar
    #  Настройки Jolokia
    command: >
      sh -c "java $JAVA_OPTS -jar plug_get_post-0.0.1-SNAPSHOT.jar"

  jolokia:
    image: jolokia/java-jolokia
    ports:
      - "8778:8778" # Порт для Jolokia
    environment:
      - JVM_OPTS=-javaagent:/docker/jolokia-agent-jvm-javaagent.jar
