services:


  postgres:
    image: postgres:12
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: 12345
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db1
      POSTGRES_INITDB_ARGS: "-A md5"
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data




  postgres-exporter:
    image: wrouesnel/postgres_exporter:latest
    environment:
      DATA_SOURCE_NAME: "user:password@tcp(postgres:5432)/"
    ports:
      - "9187:9187"
    depends_on:
      - postgres

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - postgres-exporter


volumes:
  postgres_data: